spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


application:
  version: @application.version@

spring.flyway.locations: classpath:db/migration/postgresql
spring.jpa.hibernate.ddl-auto: update

tpsf:
  base:
    url: https://tps-forvalteren-u2.nais.preprod.local/api/v1/dolly/testdata